//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONEXAOQR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Atividades
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Atividades()
        {
            this.GestaoLeadsAtividades = new HashSet<GestaoLeadsAtividades>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public string observacao { get; set; }
        public int TipoAtividadeId { get; set; }
        public int SituacaoId { get; set; }
    
        public virtual TipoAtividade TipoAtividade { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GestaoLeadsAtividades> GestaoLeadsAtividades { get; set; }
        public virtual Situacao Situacao { get; set; }
    }
}
