//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONEXAOQR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Corretor
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Corretor()
        {
            this.GestaoLeads = new HashSet<GestaoLeads>();
        }
    
        public int Id { get; set; }
        public string nome { get; set; }
        public string telefone { get; set; }
        public string email { get; set; }
        public System.DateTime dtCadastro { get; set; }
        public Nullable<System.DateTime> dtNascimento { get; set; }
        public Nullable<int> FilialId { get; set; }
        public int EmpresaId { get; set; }
        public int tipoPessoa { get; set; }
    
        public virtual Filial Filial { get; set; }
        public virtual Empresa Empresa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GestaoLeads> GestaoLeads { get; set; }
    }
}
