//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONEXAOQR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Empresa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Empresa()
        {
            this.GestaoLeads = new HashSet<GestaoLeads>();
            this.Filial = new HashSet<Filial>();
            this.Corretor = new HashSet<Corretor>();
        }
    
        public int Id { get; set; }
        public string nome { get; set; }
        public string cnpj { get; set; }
        public string email { get; set; }
        public string telefone { get; set; }
        public string endereco { get; set; }
        public string nomeFantasia { get; set; }
        public string gerente { get; set; }
        public string diretor { get; set; }
        public string mqi { get; set; }
        public string crm { get; set; }
        public string site { get; set; }
        public Nullable<int> RedesSociaisId { get; set; }
        public int TipoNegocioId { get; set; }
    
        public virtual RedesSociais RedesSociais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GestaoLeads> GestaoLeads { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Filial> Filial { get; set; }
        public virtual TipoNegocio TipoNegocio { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Corretor> Corretor { get; set; }
    }
}
