//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONEXAOQR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EtapaFunil
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EtapaFunil()
        {
            this.FaseEtapaFunil = new HashSet<FaseEtapaFunil>();
            this.LeadEtapa = new HashSet<GestaoLeadEtapaFunil>();
            this.EtapaPocentagemEmpresa = new HashSet<EtapaEmpresa>();
        }
    
        public int Id { get; set; }
        public string nome { get; set; }
        public string porcentagem { get; set; }
        public string cor { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FaseEtapaFunil> FaseEtapaFunil { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GestaoLeadEtapaFunil> LeadEtapa { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EtapaEmpresa> EtapaPocentagemEmpresa { get; set; }
    }
}
