//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONEXAOQR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EtapaEmpresa
    {
        public int Id { get; set; }
        public string etapa { get; set; }
        public string porcentagem { get; set; }
        public Nullable<int> EmpresaId { get; set; }
        public Nullable<int> EtapaFunilId { get; set; }
        public string atividades { get; set; }
        public string notaPassagem { get; set; }
        public string objetivo { get; set; }
    
        public virtual Empresa Empresa { get; set; }
        public virtual EtapaFunil EtapaFunil { get; set; }
    }
}
