//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONEXAOQR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GestaoLeadEtapaFunil
    {
        public int Id { get; set; }
        public int GestaoLeadsId { get; set; }
        public int EtapaFunilId { get; set; }
        public string dtEntrada { get; set; }
    
        public virtual EtapaFunil EtapaFunil { get; set; }
    }
}
