//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONEXAOQR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GestaoLeadsAtividades
    {
        public int Id { get; set; }
        public int AtividadesId { get; set; }
        public int GestaoLeadsId { get; set; }
    
        public virtual Atividades Atividades { get; set; }
        public virtual GestaoLeads GestaoLeads { get; set; }
    }
}
