//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CONEXAOQR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PiramideSucesso
    {
        public int Id { get; set; }
        public string meta { get; set; }
        public string ir { get; set; }
        public string obj1 { get; set; }
        public string obj2 { get; set; }
        public string obj3 { get; set; }
        public string obj4 { get; set; }
        public string obj5 { get; set; }
        public string atitude1_obj1 { get; set; }
        public string atitude2_obj1 { get; set; }
        public string atitude3_obj1 { get; set; }
        public string atitude4_obj1 { get; set; }
        public string atitude5_obj1 { get; set; }
        public string atitude1_obj2 { get; set; }
        public string atitude2_obj2 { get; set; }
        public string atitude3_obj2 { get; set; }
        public string atitude4_obj2 { get; set; }
        public string atitude5_obj2 { get; set; }
        public string atitude1_obj3 { get; set; }
        public string atitude2_obj3 { get; set; }
        public string atitude3_obj3 { get; set; }
        public string atitude4_obj3 { get; set; }
        public string atitude5_obj3 { get; set; }
        public string atitude1_obj4 { get; set; }
        public string atitude2_obj4 { get; set; }
        public string atitude3_obj4 { get; set; }
        public string atitude4_obj4 { get; set; }
        public string atitude5_obj4 { get; set; }
        public string atitude1_obj5 { get; set; }
        public string atitude2_obj5 { get; set; }
        public string atitude3_obj5 { get; set; }
        public string atitude4_obj5 { get; set; }
        public string atitude5_obj5 { get; set; }
        public Nullable<System.DateTime> dtCriacao { get; set; }
        public Nullable<System.DateTime> dtUltimoUpdate { get; set; }
        public Nullable<bool> ativo { get; set; }
        public Nullable<bool> metaBatida { get; set; }
        public string observacao { get; set; }
        public Nullable<bool> codValidado { get; set; }
        public Nullable<int> codUsuarioValidou { get; set; }
        public Nullable<int> codUsuarioCriou { get; set; }
        public Nullable<int> EmpresaId1 { get; set; }
        public Nullable<int> EmpresaId { get; set; }
    
        public virtual Empresa Empresa1 { get; set; }
        public virtual Empresa EmpresaSet { get; set; }
    }
}
